POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "airbone5",
    "email": "keshav@mail.com",
    "password": "abc123"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "keshav@mail.com",
    "password": "abc123"
}

###

GET http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Nzk1ZjA4ZmMyMjE0YjgxZmViYTdkZCIsImlhdCI6MTczNjAwODA2OCwiZXhwIjoxNzM2MDk0NDY4fQ.Tza7hEUDufofrCloyhFYHPQLDL30uTrBRb6uqKjUNfk

###

POST http://localhost:3000/api
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Nzk1ZjA4ZmMyMjE0YjgxZmViYTdkZCIsImlhdCI6MTczNjAwODA2OCwiZXhwIjoxNzM2MDk0NDY4fQ.Tza7hEUDufofrCloyhFYHPQLDL30uTrBRb6uqKjUNfk
Content-Type: application/json

{
    "title": "something",
    "description": "dasdads",
    "author": "adasd",
    "manga": "naruto",
    "cover": "naruto-cover",
    "license": true
}