POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "airbone25",
    "email": "keshav12@mail.com",
    "password": "abc123"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "keshav12@mail.com",
    "password": "abc123"
}